### ISSUE TITLE
HostNotFound: -F /etc/ceph/config 

### ISSUE THREAD

**Issue by dthpulse** [sebastian-philipp/vagrant-ceph-ssh-orchestrator#1]
Hi,
I have following in my ssh_conifg:

```
Host cephubu1
  HostName 192.168.121.91
  User root
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /etc/ceph/id_rsa
  IdentitiesOnly yes
  LogLevel FATAL

Host cephubu2
  HostName 192.168.121.45
  User root
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /etc/ceph/id_rsa
  IdentitiesOnly yes
  LogLevel FATAL

Host cephubu3
  HostName 192.168.121.60
  User root
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /etc/ceph/id_rsa
  IdentitiesOnly yes
  LogLevel FATAL

Host cephubu4
  HostName 192.168.121.243
  User root
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /etc/ceph/id_rsa
  IdentitiesOnly yes
  LogLevel FATAL
```

then in ceph config:

```
# ceph config get mgr.
WHO MASK LEVEL    OPTION                            VALUE            RO
mgr      advanced mgr/orchestrator_cli/orchestrator ssh              *
mgr      advanced mgr/ssh/ssh_config_file           /etc/ceph/config *
```

```
# ceph orchestrator status
Backend: ssh
Available: True
```

But when trying to do enything with orchestrator getting:

```
# ceph orchestrator device ls
Error EINVAL: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/mgr_module.py", line 983, in _handle_command
    return CLICommand.COMMANDS[cmd['prefix']].call(self, cmd, inbuf)
  File "/usr/share/ceph/mgr/mgr_module.py", line 372, in call
    return self.func(mgr, **kwargs)
  File "/usr/share/ceph/mgr/orchestrator_cli/module.py", line 20, in wrapper
    return func(*args, **kwargs)
  File "/usr/share/ceph/mgr/orchestrator_cli/module.py", line 103, in _list_devices
    for inventory_node in completion.result:
  File "/usr/share/ceph/mgr/ssh/module.py", line 39, in result
    return list(map(lambda r: r.get(), self._result))
  File "/usr/share/ceph/mgr/ssh/module.py", line 39, in <lambda>
    return list(map(lambda r: r.get(), self._result))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
HostNotFound: -F /etc/ceph/config cephubu3
```

However running ssh against host works:

```
root@cephubu1:~# ssh -F /etc/ceph/config cephubu3
Last login: Sun Jan 31 06:48:23 2021 from 192.168.121.91
root@cephubu3:~#
```

Thanks!

**Comment by sebastian-philipp** [comment]
Hi @dthpulse , something is odd here. Is this something you're interested? I'm wondering, cause the trackbacks look kinda outdated.

**Comment by dthpulse** [comment]
Hi @sebastian-philipp  yes I'm. I know it's Nautilus ... but I would like to fix it on our Ceph ... if it would be possible. 
Thx!

**Comment by sebastian-philipp** [comment]
The Nautilus ssh orchestrator was a prototype for cephadm later on. Note that we never implemented any upgrade from mgr/ssh to Octopus. That said, having no proper error message form remoto is still something that bothers me. In cephadm, we ended up simply replacing the (super unhelpful) error message of remoto with this text:

https://github.com/ceph/ceph/blob/639fac3564737a1a1d8322e29e5c034f73df790b/src/pybind/mgr/cephadm/serve.py#L1062-L1072

hope that helps.

**Comment by dthpulse** [comment]
yep, this is something I have tried before I placed an issue here :) and ssh to host from CLI using private key works 

```
root@cephubu1:~# ssh -F /etc/ceph/config cephubu3
Last login: Sun Jan 31 06:48:23 2021 from 192.168.121.91
root@cephubu3:~#
```

however it looks like the error is a bit different here it says `HostNotFound: -F /etc/ceph/config cephubu3` what looks like it's trying to resolve whole string as host `-F /etc/ceph/config cephubu3` and not just a `cephubu3`.

**Comment by sebastian-philipp** [comment]
u're sure mgr/ssh uses the same private key?
